**Q1 . List Operation**

In [2]:
numbers = [40, 10, 30, 20, 50]
print("Original Lists:", numbers)

# append
numbers.append(60)
print("After append(60):", numbers)

# extend
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# insert
numbers.insert(0, 5)
print("After insert(0,5):", numbers)

# remove
numbers.remove(30)
print("After remove(30):", numbers)

# pop
popped = numbers.pop()
print("After pop():", numbers, "| Popped value:", popped)

# index
print("Index of 20:", numbers.index(20))

# count
print("Count of 10:", numbers.count(10))

# sort
numbers.sort()
print("After sort():", numbers)

# reverse
numbers.reverse()
print("After reverse():", numbers)

# clear
numbers.clear()
print("After clear():", numbers)

Original Lists: [40, 10, 30, 20, 50]
After append(60): [40, 10, 30, 20, 50, 60]
After extend([70, 80]): [40, 10, 30, 20, 50, 60, 70, 80]
After insert(0,5): [5, 40, 10, 30, 20, 50, 60, 70, 80]
After remove(30): [5, 40, 10, 20, 50, 60, 70, 80]
After pop(): [5, 40, 10, 20, 50, 60, 70] | Popped value: 80
Index of 20: 3
Count of 10: 1
After sort(): [5, 10, 20, 40, 50, 60, 70]
After reverse(): [70, 60, 50, 40, 20, 10, 5]
After clear(): []


**Q2. Tuple Immutability**

In [3]:
students = ("Alice", "Bob", "Charlie")
print("Tuple:", students)

try:
    students[1] = "David"
except TypeError as e:
    print("Error:", e)

Tuple: ('Alice', 'Bob', 'Charlie')
Error: 'tuple' object does not support item assignment


**Q3. Set with Duplicates**

In [4]:
numbers_set = {1, 2, 2, 3, 4, 4, 4, 5}
print("Set:", numbers_set)
print("Type:", type(numbers_set))

Set: {1, 2, 3, 4, 5}
Type: <class 'set'>


**Q4. Dictionary Update**

In [5]:
person = {
    "name": "Ravi",
    "age": 25,
    "city": "Mumbai"
}
print("Original dictionary:", person)

person["age"] = 26

person["email"] = "ravi@example.com"

print("Updated dictionary:", person)

Original dictionary: {'name': 'Ravi', 'age': 25, 'city': 'Mumbai'}
Updated dictionary: {'name': 'Ravi', 'age': 26, 'city': 'Mumbai', 'email': 'ravi@example.com'}


**Q5. Voting Eligibility**

In [6]:
age = 20

if age >= 18:
    print(f"Age {age}: Eligible to vote.")
else:
    print(f"Age {age}: Not eligible to vote.")

Age 20: Eligible to vote.


**Q6. Grade Calculator**

In [7]:
marks = 82

if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

print(f"Marks: {marks} → Grade: {grade}")

Marks: 82 → Grade: B


**Q7. Positive / Even / Zero / Negative Check**

In [8]:
num = 12

if num > 0:
    print(f"{num} is positive.")
    if num % 2 == 0:
        print(f"{num} is also even.")
    else:
        print(f"{num} is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print(f"{num} is negative.")

12 is positive.
12 is also even.


**Section B : Numpy**

**Q8. Create Scalar, 1D Array, and 2D Array**

In [11]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar, "| ndim:", scalar.ndim)

# 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d, "| ndim:", arr_1d.ndim)

# 2D array (2x3) with values 10 to 60 in steps of 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D array:\n", arr_2d, "| shape:", arr_2d.shape)

Scalar: 5 | ndim: 0
1D array: [1 2 3 4 5] | ndim: 1
2D array:
 [[10 20 30]
 [40 50 60]] | shape: (2, 3)


**Q9. Random 4×4 Integer Array**

In [13]:
random_arr = np.random.randint(0, 101, size=(4, 4))
print("Random 4x4 array:\n", random_arr)

Random 4x4 array:
 [[52 27 10 34]
 [31 40 10 57]
 [84 42 43 67]
 [89 10 32 22]]


**Q10. NumPy 2D → Pandas DataFrame**

In [14]:
import pandas as pd

# 3x3 NumPy array
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Convert to DataFrame with column names
df = pd.DataFrame(arr_3x3, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


**Section C: Exploring Pandas**

**Q11. DataFrame with 10 Rows — Full Workflow**

In [15]:
import pandas as pd
import numpy as np

data = {
    'Name':   ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vikram',
               'Amit', 'Neha', 'Karan', 'Priya', 'Meera'],
    'Age':    [25, 30, 28, 22, 35, 25, 27, 32, 30, np.nan],
    'City':   ['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Pune',
               'Delhi', 'Jaipur', 'Mumbai', 'Mumbai', 'Indore'],
    'Salary': [50000, 60000, np.nan, 45000, 70000,
               50000, 55000, np.nan, 60000, 48000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
      Name   Age     City   Salary
0    Amit  25.0    Delhi  50000.0
1   Priya  30.0   Mumbai  60000.0
2   Rahul  28.0  Chennai      NaN
3   Sneha  22.0  Kolkata  45000.0
4  Vikram  35.0     Pune  70000.0
5    Amit  25.0    Delhi  50000.0
6    Neha  27.0   Jaipur  55000.0
7   Karan  32.0   Mumbai      NaN
8   Priya  30.0   Mumbai  60000.0
9   Meera   NaN   Indore  48000.0
